### ISSUE TITLE
iCal Generator Doesn't Append .ics in firefox

### ISSUE THREAD

**Issue by khaledallen** [donaldwasserman/ember-add-calendar-button#1]
Downloaded file from the ical generator button doesn't append .ics to the end of the file, and thus can't be used by ical unless the extension is added manually. Works fine in Chrome (not tested in Safari or IE).

Firefox's download manager does recognize the file type, but doesn't do anything with it ("Open with" does nothing), and the file in the finder has no extension and opens with a text editor. Forcing it to open with Calendar has no result until the extension is added.

Not sure if this is something that can be addressed but sharing the discovery.

**Comment by donaldwasserman** [comment]
Hey - @khaledallen Thanks for pointing this out. I'll try to cut a fix today. What version of firefox are you using?

I didn't get notified about this for some reason.

**Comment by donaldwasserman** [comment]
Fixed in 0.0.4

**Comment by khaledallen** [comment]
I guess you already address this, but FYI I am running 57.0.4 (64-bit)
